theme: jekyll-theme-minimal
title: Student online portfolio 
description: digital portfolio shifts the focus from "What grade did I get?" to "What did I learn and what can I do?" It transforms a collection of assignments into a coherent story of personal and professional development.
